# Generated by Django 4.0.5 on 2022-06-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('no_of_seats', models.IntegerField(null=True)),
                ('ac', models.BooleanField(default=False)),
            ],
        ),
    ]
